### ISSUE TITLE
Migrate core + shuttle infrastructure away from Equinix

### ISSUE THREAD

**Issue by Zorlin** [application-research/estuary-hosted-infrastructure#12]
```[tasklist]
### Tasks
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/30
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/21
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/32
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/31
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/33
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/29
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/28
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/27
- [ ] https://github.com/application-research/estuary-hosted-infrastructure/issues/26
```

**Comment by Zorlin** [comment]
Done
